### ISSUE TITLE
Updating user password does not work in cluster mode

### ISSUE THREAD

**Issue by vitrez** [ansible-collections/community.clickhouse#104]
##### SUMMARY

When updating the user password `cluster` directive is not applied. The module source code does not contain clause `ON CLUSTER`. The user password is updated only on one node - on login host.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.clickhouse.clickhouse_user

##### COLLECTION VERSION

```
community.clickhouse:          0.8.1 

```

##### OS / ENVIRONMENT

Target OS version: Oracle Linux

##### STEPS TO REPRODUCE

```yaml
- name: Config | Create admin user
  register: result
  community.clickhouse.clickhouse_user:
    login_host: ch-01
    login_user: default
    login_password: ''
    cluster: "{{ cluster_name }}"
    name: admin
    password: "{{ clickhouse_admin_password }}"
    update_password: always
    state: present
  delegate_to: 127.0.0.1
  run_once: true
```

##### EXPECTED RESULTS

Successful connection to all three cluster nodes: 
- ch-01
- ch-02
- ch-03

##### ACTUAL RESULTS

I successfully connect to only one node, the one specified in the `login_host`.
The other nodes failed to connect successfully, for example:
```
# clickhouse-client -h ch-02 -u admin --ask-password
ClickHouse client version 25.4.4.25 (official build).
Password for user (admin):
Connecting to ch-02:9000 as user admin.
Code: 516. DB::Exception: Received from ch-02:9000. DB::Exception: admin: Authentication failed: password is incorrect, or there is no user with such name.. (AUTHENTICATION_FAILED)
```
