### ISSUE TITLE
Error creating database when specifying engine type

### ISSUE THREAD

**Issue by vitrez** [ansible-collections/community.clickhouse#107]
##### SUMMARY
When creating a database **with an engine type specified**, an error appears indicating invalid syntax:

`DB::Exception: Syntax error: failed at position 38 (ON): ON CLUSTER default`

The problem is in the invalid position of clause `ON CLUSTER` in the query. It must be [before](https://clickhouse.com/docs/sql-reference/statements/create/database) the engine type.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.clickhouse.clickhouse_db

##### COLLECTION VERSION

```
community.clickhouse:          0.8.2

```

##### OS / ENVIRONMENT

Target OS version: `Oracle Linux`

##### STEPS TO REPRODUCE

```yaml
- name: Config | Manage databases
  community.clickhouse.clickhouse_db:
    login_host: "{{ clickhouse_login_host }}"
    login_user: "{{ clickhouse_admin_username }}"
    login_password: "{{ clickhouse_admin_password }}"
    cluster: "default"
    name: 'test'
    engine: 'Atomic'
    state: 'present'
  delegate_to: 127.0.0.1
  run_once: true

```

##### EXPECTED RESULTS

The database is created and the playbook runs without errors.

##### ACTUAL RESULTS

```
TASK [clickhouse-keeper : Config | Manage databases] *********************************************************************************************************
failed: [ch-01.test-ra-dks.mts-corp.ru -> 127.0.0.1] (item={'name': 'test', 'engine': 'Atomic'}) => changed=false 
  ansible_loop_var: item
  item:
    engine: Atomic
    name: test
  msg: |-
    Failed to execute query: Code: 62.
    DB::Exception: Syntax error: failed at position 38 (ON): ON CLUSTER default. Expected one of: token sequence, Dot, token, OpeningRoundBracket, PARTITION BY, PRIMARY KEY, ORDER BY, SAMPLE BY, TTL, SETTINGS, COMMENT, table overrides declaration list, table override declaration, TABLE OVERRIDE, INTO OUTFILE, FORMAT, ParallelWithClause, PARALLEL WITH, end of query.
```
