### ISSUE TITLE
clickhouse_cfg_info hangs indefinitely and exhausts memory on YAML files with recursive anchors

### ISSUE THREAD

**Issue by gdrosos** [ansible-collections/community.clickhouse#111]
##### SUMMARY
The `community.clickhouse.clickhouse_cfg_info` module hangs indefinitely when given a YAML file with a recursive anchor (alias loop). This results in the entire playbook stalling. While hanging, the task also continuously consumes memory, eventually exhausting system resources if left running. This may constitute a denial-of-service risk if the module is used with untrusted or user-generated YAML files, due to the unbounded resource consumption and indefinite hang triggered by recursive anchors.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
clickhouse_cfg_info

##### ANSIBLE VERSION
```paste below
ansible [core 2.18.3]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /venv3.12/lib/python3.12/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /venv3.12/bin/ansible
  python version = 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0] (/venv3.12/bin/python)
  jinja version = 3.1.6
  libyaml = True

```

##### COLLECTION VERSION

```paste below
Collection           Version
-------------------- -------
community.clickhouse 0.8.3  
```

##### OS / ENVIRONMENT

Reproduced on Ubuntu 24.04

##### STEPS TO REPRODUCE

```yml
- name: Prepare YAML config with recursive alias (invalid)
  ansible.builtin.copy:
    dest: /tmp/cfg_recursive.yaml
    content: |
      a: &a
        b: *a

- name: Try to retrieve YAML config with recursive alias
  register: recursive_yaml_result
  community.clickhouse.clickhouse_cfg_info:
    path: /tmp/cfg_recursive.yaml
  ignore_errors: true

- name: Assert recursive alias in YAML fails
  ansible.builtin.assert:
    that:
    - recursive_yaml_result.failed
```

##### EXPECTED RESULTS

The module should detect the invalid recursive alias in the YAML file, fail immediately, and return a clear error message. It must not hang or consume unbounded resources.

##### ACTUAL RESULTS

The task `Try to retrieve YAML config with recursive alias` hangs indefinitely when attempting to parse the YAML file. No error is thrown, and the playbook is stalled until manually interrupted. 
While hanging, the task continuously consumes more memory over time (can validate via  `watch -n 1 free -h`), which can eventually lead to full system memory exhaustion.
```
PLAY [localhost] ************************************************************************************************************************************************

TASK [Prepare YAML config with recursive alias (invalid)] *******************************************************************************************************
changed: [localhost]

TASK [Try to retrieve YAML config with recursive alias] *********************************************************************************************************
```
