### ISSUE TITLE
Execution of sql scripts

### ISSUE THREAD

**Issue by aleksvagachev** [ansible-collections/community.clickhouse#26]
##### SUMMARY
It may not be convenient to use the clickhouse_client module to create tables or more complex queries. Maybe it's worth implementing a module for reading and executing scripts, or adding script execution functionality to clickhouse_client?

##### ISSUE TYPE
- Feature Idea

**Comment by Andersson007** [comment]
@aleksvagachev i don't know how it works in clickhouse but if they support something like dump / restore in other RDBMS maybe we should create a module for that (i don't like this to be like in c.postgres/mysql where it's done via _db modules). E.g. possible interface
```
- name: Dump data
  community.clickhouse.clickhouse_data:
    state: dump
    file: /path/to/file

- name: Restore data
  community.clikhouse.clickhouse_data:
    state: restore
    file: /path/to/file
```
the module name, the args names, and choices can be discussed but the idea should be clear. I would like to mix it with `clickhouse_db` module and this would solve your issue. But i'm not an expert.
What do you think?
