### ISSUE TITLE
Error creating user with grant_role

### ISSUE THREAD

**Issue by xkostix** [ansible-collections/community.clickhouse#97]
##### SUMMARY

Using plugin clickhouse_user to create user and grant role. Ansible returns error:
"'ClickHouseUser' object has no attribute '_ClickHouseUser__grant_role'. Did you mean: '_ClickHouseUser__grant_roles'?"

Cause is in string 296 of /plugins/modules/clickhouse_user.py
calling method "__grant_role":
`self.__grant_role(roles)`

While there is method "__grant_roles" in the code in string 395:
`def __grant_roles`

Note: I added letter 's' to the string 296 to get like this: "__grant_roles(roles)".
And I got working properly plugin, working OK.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

clickhouse_user.py

##### ANSIBLE VERSION

```
ansible [core 2.17.9]
python version = 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0] (/usr/bin/python3)
jinja version = 3.0.3
libyaml = True
```

##### COLLECTION VERSION

```
community.clickhouse-0.7.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 22.04

##### STEPS TO REPRODUCE

```
- name: Create ClickHouse user if not exists
  community.clickhouse.clickhouse_user:
    name: "{{ username }}"
    password: "{{ passw }}"
    roles:
    - "{{ role_name }}"
    default_roles:
    - "{{ role_name }}"
    state: present
    update_password: always
    roles_mode: listed_only
    default_roles_mode: listed_only
    login_user: "default"
    login_password: "{{ clickhouse_password }}"
```

##### EXPECTED RESULTS

Expect to create user, and to grant role and default_role.

##### ACTUAL RESULTS

Creates user. But does not grant role and default_role.
```
Error:
'ClickHouseUser' object has no attribute '_ClickHouseUser__grant_role'. Did you mean: '_ClickHouseUser__grant_roles'?
```
